### ISSUE TITLE
Add door or hole that loads next level

### ISSUE THREAD

**Issue by diaboloshogunate** [diaboloshogunate/Psyforce#29]
have it be a hole for now. hopefully we will get a sprite to add in

**Comment by sirslade** [comment]
Added, but not quite perfect. I want to add an extended black hallway that the player must walk into before it marks the win state. It might also be good to only mark the entering player as in win state and deactivate their controls, then proceed to the next level when both players are in their respective hallways.
Should probably also give it a slight glow to indicate that it's the objective.
