### ISSUE TITLE
update game over scene

### ISSUE THREAD

**Issue by diaboloshogunate** [diaboloshogunate/Psyforce#32]
use ranis image with a black background. if Ben creates music, add it in as well.

**Comment by sirslade** [comment]
Background is currently white, but added it to the game over screen. Working on music next (Will need to update the script to stop the current BGM before opening the gameOver screen and playing the new music.)

**Comment by sirslade** [comment]
Music added (As well as some other QOL improvements like killing the other player on game over and stopping all audio when the game over screen is displayed)
